import type { Metadata } from "next";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='font-inter bg-bg text-text overflow-x-hidden h-screen  px-4 xl:px-8'>
        <Nav />
        <main>
        {children}
        </main>
        
        <Footer />
      </body>
    </html>
  );
}
